Rails.application.config.assets.precompile += %w( application/login.js )
Rails.application.config.assets.precompile += %w( application/app.js )
Rails.application.config.assets.precompile += %w( application/user/sites.js )
Rails.application.config.assets.precompile += %w( application/user/config.js )
Rails.application.config.assets.precompile += %w( application/device/report.js )
Rails.application.config.assets.precompile += %w( glyphicons-halflings-regular.*)