# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  host: lppurchase.ccasi6w4s7bm.us-east-1.rds.amazonaws.com
  database: loonmedical_dev
  pool: 5
  username: maws
  password: G30rg14*

test:
    adapter: postgresql
    host: localhost
    database: loonmedical_test
    pool: 5
    username: postgres
    password: pwd

production:
      host: localhost
      adapter: postgresql
      database: loonmedical_prod
      pool: 5
      username: postgres
      password: pwd